// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkayjngfzatwrejndull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYXlqbmdmemF0d3Jlam5kdWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODA3MTcsImV4cCI6MjA1NTI1NjcxN30.l8ODfig64uPYvWmnCyfuZWh0WUBC8wcuEw9CU6TqIEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);